name: Check PR title
on:
  # SAFETY: dfinity/conventional-pr-title-action does not run any of the committed code.
  # Therefore it is ok to give it R/W permission.
  # More details see here: https://securitylab.github.com/research/github-actions-preventing-pwn-requests/
  pull_request_target:
    types:
      - opened
      - reopened
      - edited
      - synchronize

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  # When getting Rust dependencies, retry on network error:
  CARGO_NET_RETRY: 10
  # Use the local .curlrc
  CURL_HOME: .

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Conventional PR title
        # Conventional commit patterns:
        #   verb: description
        #   verb!: description of breaking change
        #   verb (scope): Description of change to $scope
        #   verb (scope)!: Description of breaking change to $scope
        # verb: feat, fix, ...
        # scope: refers to the part of code being changed.  E.g. " (accounts)" or " (accounts,canisters)"
        # !: Indicates that the PR contains a breaking change.
        run: commit="${{ github.event.pull_request.title }}" perl -E 'exit !($ENV{commit} =~ /^(feat|fix|chore|build|ci|docs|style|refactor|perf|test)( \([a-zA-Z0-9,]+\))?!?:.*/)' ; echo $?
        if: github.event_name == 'pull_request'
